### ISSUE TITLE
Should we add a company who doesn't respect 100% GPL?

### ISSUE THREAD

**Issue by miya0001** [wp-core-php/servehappy-resources#12]
There is a hosting company which is marketing with a theme developer.
And the theme developer doesn't respect 100% GPL.

Should we add this hosting company to the list of hosting-specific tutorials?
https://github.com/wp-core-php/servehappy-resources/blob/master/tutorials/hosting-specific/tutorials-ja.md

* The hosting company isn't selling this theme. (probably ...)
* They are making advertising with this theme.

I am thinking we should add this hosting company to the list to protect their users.

**Comment by felixarntz** [comment]
I agree it makes sense to add it, as we're not promoting specific companies here, we only want to help users on as many hosts possible.

**Comment by miya0001** [comment]
@felixarntz Thanks! That's a relief. I'm glad to hear that.
