### ISSUE TITLE
Idea: Update button in backend

### ISSUE THREAD

**Issue by ScreamingDev** [wp-core-php/servehappy-resources#22]
Catchy title, isn't it?

If we can determine the server (by resolving the hostname of whois for example)
then the backend could contain a button to such tutorials how to update PHP versions.
A short intro what this is, why it needs to be done by hand, etc.

So nice having this button nagging there ;)

**Comment by schlessera** [comment]
As described in https://make.wordpress.org/core/2019/01/14/php-site-health-mechanisms-in-5-1/, we do have a button in the backend now, and it can be customized by the hosting provider that hosts your server to point to their own customized resource.
