### ISSUE TITLE
any tutorials on php upgradation on gcp

### ISSUE THREAD

**Issue by binnythap** [wp-core-php/servehappy-resources#40]
Hi I was looking forward for also a tutorial on sites hosted on Google Cloud Platform, probably installed via Marketplace using Google click to deploy as well as bitnami.

Thanks!

**Comment by ePascalC** [comment]
Bitnami instances normally are not upgraded. You just recreate one based on a new PHP version. See this answer from a bitnami engineer: _There is not any straightforward way of updating the base components as it requires to recompile that base component from scratch and you will find several issues during that process. However you can upgrade the base components of your solution by launching a new instance with the new version of PHP and migrating your application data from the old deployment to the new one._
