### ISSUE TITLE
Please Help me Update! T_T

### ISSUE THREAD

**Issue by DarylReyes** [wp-core-php/servehappy-resources#75]
Dear Hosting Provider,

I want my website to be as performant and secure as
possible with the latest version of PHP. For the server
my WordPress site is hosted on, I want to ensure that
is the case. If I am not already on the latest version
of PHP, please let me know what steps I need to take
to update.

Thanks!

**Comment by connieiloh** [comment]
Dear Gigalayer,

I want my website to be as performant and secure as
possible with the latest version of PHP. For the server
my WordPress site is hosted on, I want to ensure that
is the case. If I am not already on the latest version
of PHP, please let me know what steps I need to take
to update.

Thanks!
comsycybercity@yahoo.com for domain name georgemoghalu.org
georgemoghalu.org
