### ISSUE TITLE
Flagging issues with specific tutorials?

### ISSUE THREAD

**Issue by OldGuyInTheClub** [wp-core-php/servehappy-resources#76]
Is it possible to flag incorrect/incomplete information on specific tutorials?

e.g. The link to HostGator shows how to update the PHP version but, at least for me, that results in a broken site.  Per WP support, MySQLND needs to be enabled for to go from PHP 5.4 (HG default) to 7.x, and there does not seem to be a way to do that on HostGator.

**Comment by ePascalC** [comment]
@OldGuyInTheClub I think it's now pointing to the correct one. Can you confirm? Thanks.

**Comment by OldGuyInTheClub** [comment]
I left HostGator for another provider some time ago and can no longer check. I had forgotten about this issue.  I'll close it.
